feat: added time config for max issue
ubiquity/ubiquibot pull request #393
Opened 2023-06-13 04:02 UTC by wannacfuture

Resolves #388 
Test successful.
You can see the test result at https://github.com/wannacfuture/Battleship/issues/19
There, I can't assign to that issue even I have one pull request which is created over 24 hours before, because TIME_RANGE_FOR_MAX_ISSUE_ENABLED was set `false` so bot doesn't count PRs.
Also I added TIME_RANGE_FOR_MAX_ISSUE for flexible time configuration for max-bounty-issue.

2023-06-13 04:31 UTC, pavlovcik commented on src/helpers/issue.ts
>  export const getOpenedPullRequestWithNoReviewsOver24HoursPassedAfterCreated = async (username: string) => {
To increase code clarity I recommend splitting this into separate functions `getOpenedPullRequests` 
- and then filter by no reviews i.e. `noReviews` 
- and then filter again by `timePassed`

2023-06-13 04:32 UTC, pavlovcik commented on src/configs/shared.ts
> +export const TIME_RANGE_FOR_MAX_ISSUE_ENABLED = true;
```suggestion
export const DEFAULT_TIME_RANGE_FOR_MAX_ISSUE = 24;
export const DEFAULT_TIME_RANGE_FOR_MAX_ISSUE_ENABLED = true;
```

2023-06-13 04:33 UTC, pavlovcik requested changes
Left comments.

2023-06-13 08:26 UTC, wannacfuture commented
> Left comments.

@pavlovcik , fixed.

2023-06-13 17:51 UTC, 0xcodercrane commented
The codebase looks good to me. @Draeieg  would you be handling the QA with @wannacfuture  here?

2023-06-13 17:51 UTC, 0xcodercrane approved these changes

2023-06-13 17:54 UTC, Draeieg commented
> The codebase looks good to me. @Draeieg  would you be handling the QA with @wannacfuture  here?

He already provided an example QA, I'd say we can merge to development and I'll replicate in staging just to be sure

2023-06-14 01:12 UTC, merged

2023-06-24 08:49 UTC, ubiquity-bounties commented on src/handlers/comment/handlers/assign.ts
>    logger.info(`Opened Pull Requests with no reviews but over 24 hours have passed: ${JSON.stringify(opened_prs)}`);
This log comment should be updated because the `24 hours` is configurable.  @wannacfuture