Fix: 0 considered as false
ubiquity/ubiquibot pull request #411
Opened 2023-06-16 08:27 UTC by 0xcodercrane

Resolves #

2023-06-17 02:13 UTC, 0xcodercrane commented
QA: https://github.com/ubiquibot/staging/issues/31

2023-06-18 05:27 UTC, pavlovcik approved these changes

2023-06-18 16:32 UTC, pavlovcik requested changes
https://github.com/ubiquibot/staging/issues/31#issuecomment-1596194441

2023-06-19 02:58 UTC, merged

2023-06-19 15:58 UTC, 0xcodercrane commented on src/handlers/payout/action.ts
> +    return `Refusing to generate the payment permit because @${assignee.login} payment multiplier is 0`;
`Why not use a string variable and then use it twice?
`
we have similar things in several places. so I'd like to process them at once

2023-06-19 17:42 UTC, pavlovcik commented on src/handlers/payout/action.ts
> +    return `Refusing to generate the payment permit because @${assignee.login} payment multiplier is 0`;
Will you be able to address the changes I requested?

2023-06-20 01:08 UTC, 0xcodercrane commented on src/handlers/payout/action.ts
> +    return `Refusing to generate the payment permit because @${assignee.login} payment multiplier is 0`;
> Will you be able to address the changes I requested?

fixed it here. https://github.com/ubiquity/ubiquibot/commit/c5d916f079d12d0f31040b68b90b77754a00f0e0