Hotfix: add default price label when creating issue
ubiquity/ubiquibot pull request #484
Opened 2023-07-10 12:29 UTC by wannacfuture

Resolves #482 

QA example: https://github.com/wannacfuture/Battleship/issues/29

2023-07-11 14:01 UTC, pavlovcik submitted a review, later dismissed
The code checks out but @0xcodercrane is this the only condition the bot needs in order to generate a payment permit? A `Price` label?

2023-07-11 14:07 UTC, 0xcodercrane requested changes

2023-07-11 14:07 UTC, 0xcodercrane commented on src/handlers/comment/handlers/index.ts
>      return await addCommentToIssue(`Error: ${err}`, issue.number);
```suggestion
    await addCommentToIssue(`Error: ${err}`, issue.number);
```

2023-07-11 14:07 UTC, 0xcodercrane commented on src/handlers/comment/handlers/index.ts
>      return;
```suggestion
```

2023-07-11 14:07 UTC, 0xcodercrane commented on src/handlers/comment/handlers/index.ts
> +
would be better to remove duplication use of `timeLabelConfigs[0].name` and `priorityLabelConfigs[0].name`

2023-07-19 09:08 UTC, 0xcodercrane commented
Holding off the PR until the exploit issue resolved

2023-07-27 16:04 UTC, pavlovcik commented
> Holding off the PR until the exploit issue fully resolved

Can you link back an open pull request working on resolving the exploit? It seems like this pull request was forgotten about and its difficult for me to audit the progress.

2023-07-28 01:42 UTC, 0xcodercrane commented
> > Holding off the PR until the exploit issue fully resolved
> 
> Can you link back an open pull request working on resolving the exploit? It seems like this pull request was forgotten about and its difficult for me to audit the progress.

https://github.com/ubiquity/ubiquibot/commit/f4e5c65259d3bc9d7d6a1fc3468ca2b19733a624

2023-08-04 01:42 UTC, Draeieg approved these changes

2023-08-09 20:06 UTC, pavlovcik commented
Can we merge this @0xcodercrane?

2023-08-11 07:52 UTC, 0xcodercrane commented
> Can we merge this @0xcodercrane? The merge conflict is getting complicated.

Yes. let me handle it

2023-08-11 07:52 UTC, 0xcodercrane approved these changes

2023-08-11 07:52 UTC, merged