feat: default labels config
ubiquity/ubiquibot pull request #506
Opened 2023-07-13 17:34 UTC by whilefoo

Resolves #500

2023-07-13 21:08 UTC, pavlovcik commented on .github/ubiquibot-config.yml
> +      - "Priority: 0 (Normal)"
Pretty cool you implemented this but I still fear that we'll need to remove this when we implement the database style config e.g. `/default-labels @pavlovcik "Time: <1 Hour" "Priority: 0 (Normal)"

2023-07-13 21:10 UTC, pavlovcik reviewed
Code seems fine I just fear that we need to remove the user specific default label config code soon.

2023-07-13 21:10 UTC, pavlovcik commented on README.md
> +## Configuration
You did a great job here thanks.

2023-07-13 21:10 UTC, pavlovcik approved these changes

2023-07-14 08:54 UTC, 0xcodercrane submitted a review, later dismissed

2023-07-14 08:54 UTC, 0xcodercrane commented on .github/ubiquibot-config.yml
> +    pavlovcik:
oh no. seems better to use `ubiquity-bounties` instead of @pavlovcik  lol

2023-07-16 06:12 UTC, pavlovcik requested changes

2023-07-16 06:12 UTC, pavlovcik commented on .github/ubiquibot-config.yml
> +      - "Priority: 0 (Normal)"
There's one thing I forgot to highlight @whilefoo but https://github.com/ubiquity/ubiquibot/issues/500#issuecomment-1634429276 

Would you mind refactoring this config to be like this:

```suggestion
default-labels:
  - "Time: <1 Hour"
  - "Priority: 0 (Normal)"
  - "Test"
```

2023-07-16 18:54 UTC, pavlovcik approved these changes

2023-07-17 19:48 UTC, Draeieg approved these changes

2023-07-23 16:43 UTC, whilefoo commented
what's stopping this from merging?

2023-07-25 03:28 UTC, pavlovcik commented
> what's stopping this from merging?

That is unusual. GitHub iOS client UI doesn't tell me any useful information on it. @0xcodercrane do you know why

2023-07-25 03:28 UTC, merged

2023-07-25 03:54 UTC, 0xcodercrane commented
> That is unusual. GitHub iOS client UI doesn't tell me any useful information on it. @0xcodercrane do you know why

Looks like related to unresolved conversations