improve codebase: add unit testing
ubiquity/ubiquibot pull request #514
Opened 2023-07-16 06:23 UTC by molecula451

Resolves #176

2023-07-16 19:11 UTC, pavlovcik approved these changes
This seems like a pretty solid start. Thanks for your high quality first time contribution to this repository @molecula451 !

2023-07-16 19:12 UTC, pavlovcik reviewed
I reviewed my specification and I still think we should consider setting up a GitHub Actions Docker runtime. @rndquu @molecula451 curious on your input here.

2023-07-17 08:04 UTC, rndquu requested changes
Pls add more [tests](https://github.com/ubiquity/ubiquibot/issues/176#issuecomment-1637534000) along with CI test workflow

2023-07-17 11:36 UTC, molecula451 commented
> 
> We [plan](https://github.com/ubiquity/ubiquibot/issues/176#issuecomment-1637534000) to go step by step:
> 
> 1. Unit tests
> 2. Functional tests (perhaps using docker)

CI already working and testing on https://github.com/ubiquity/ubiquibot/actions/runs/5574793016/jobs/10183863908

Adding and polishing more tests

2023-07-17 11:38 UTC, molecula451 commented
> I reviewed my specification and I still think we should consider setting up a GitHub Actions Docker runtime. I haven't done a deep dive on researching these matters so I'm not 100% confident on the best way forward. The business problem I am aiming to solve is to minimize or eliminate the reliance on our manual quality assurance processes.
> 
> The worst is when pull requests pass reviews, and then bugs appear in staging/production.
> 
> @rndquu @molecula451 curious on your input here.

and I am in pair with that vision, but I remind that's why you have @rndquu and **I** for the good QA and making sure things work as of highest standard

2023-07-29 00:48 UTC, molecula451 commented on src/tests/help.test.ts
> +    expect(helpMenu).toBeTruthy();
this truthy it's better on this one as `generateHelpMenu()` is prone to change

2023-08-16 15:23 UTC, pavlovcik commented
Stale

2023-08-16 15:23 UTC, closed without merging

2023-08-16 15:37 UTC, molecula451 commented
@pavlovcik this was not at all stale thing is rndquu changed the game of the original descripción which was to create an initial base for unit testing ive opened the PR before the asked changed. That i stale a bit. But then i reincorporate and i was desigining a Payload mock testing for the commands this is not trivial and was taking time

2023-08-16 15:38 UTC, pavlovcik commented
The last update on this was 19 days ago. It doesn't look like it's being worked on anymore which is why I closed it.