feat: if no user is provided, default to sender
ubiquity/ubiquibot pull request #515
Opened 2023-07-16 06:47 UTC by me505

Resolves #513

2023-07-16 06:50 UTC, me505 commented
/help

2023-07-16 19:08 UTC, pavlovcik commented on src/handlers/comment/handlers/multiplier.ts
> +    if (username === "") {
I question this implementation. I personally would probably deliberately parse "no user" as `username === null` to express that the user value has been recognized by the system, and that it has been assigned to nothing.

2023-07-16 19:40 UTC, pavlovcik commented on src/handlers/comment/handlers/multiplier.ts
> +    if (username === "") {
Thanks, but make sure that the code actually works with this change. I would have expected that you change it to `null` somewhere else in the code when the value is being set.

2023-07-17 08:40 UTC, 0xcodercrane requested changes

2023-07-17 08:40 UTC, 0xcodercrane commented on src/handlers/comment/handlers/multiplier.ts
> +    }
```suggestion
    username = username || sender;
```

2023-07-17 13:01 UTC, me505 reviewed
thanks

2023-07-17 20:24 UTC, Draeieg approved these changes

2023-07-18 07:42 UTC, merged