build: workflow to automate the PR creation
ubiquity/ubiquibot pull request #540
Opened 2023-07-19 06:45 UTC by AnakinSkywalkeer

Resolves #357

2023-07-19 12:49 UTC, rndquu requested changes
Pls fix:
1. [QA](https://github.com/ubiquity/ubiquibot#how-to-qa-any-additions-to-the-bot) is missing
2. The original issues describes that we should compare the [default config](https://github.com/ubiquity/ubiquibot/pull/383/files#diff-3dbd906a74e6e90c70b674f19ce3a371e7c77361c9de83dc8fdf9f02750caa8b) with a partner's config but [PR](https://github.com/ubiquity/ubiquibot/pull/383) for this feature is not yet merged

2023-07-19 12:49 UTC, rndquu commented on .github/workflows/pr.yml
> +        run: sudo apt-get -y install jq
Why do we need this step?

2023-07-19 12:49 UTC, rndquu commented on .github/workflows/pr.yml
> +          declare -a repoUrls=(
Partner URLs should be dynamically fetched from https://github.com/ubiquity/devpool-directory/blob/development/projects.json

2023-07-19 12:49 UTC, rndquu commented on .github/workflows/pr.yml
> +            cp ../.github/ubiquity-bot.yml .github/ubiquity-bot.yml
`cp` rewrites the config, we need it to be updated with new parameters

2023-08-16 15:23 UTC, pavlovcik commented
Stale

2023-08-16 15:23 UTC, closed without merging