feat: update example address to 0x0
ubiquity/ubiquibot pull request #550
Opened 2023-07-27 15:16 UTC by me505

Resolves #549

2023-07-27 18:54 UTC, pavlovcik approved these changes

2023-07-27 18:54 UTC, pavlovcik commented
I'm assuming you checked for every example address across all commands?

2023-07-27 18:54 UTC, pavlovcik commented
/help

2023-07-27 18:57 UTC, pavlovcik approved these changes
I fixed the merge conflict for you.

2023-07-28 01:50 UTC, me505 commented
> I fixed the merge conflict for you.

thanks

2023-07-28 01:52 UTC, 0xcodercrane requested changes

2023-07-28 01:52 UTC, 0xcodercrane commented on src/handlers/comment/handlers/wallet.ts
> +    if (address == "0x0000000000000000000000000000000000000000"){
Avoid using the hardcoded `0x00..0` address. there should be a AddressZero constant in ethers library.

2023-07-28 04:52 UTC, me505 commented
weird, [netlify](https://app.netlify.com/sites/ubiquibot-staging/deploys/64c34834731ecf0008a20ee1) checks seems to have passed

2023-07-28 04:55 UTC, pavlovcik approved these changes

2023-07-28 08:56 UTC, 0xcodercrane approved these changes

2023-07-28 08:56 UTC, merged