fix: cap multiplier to 1
ubiquity/ubiquibot pull request #565
Opened 2023-07-30 13:17 UTC by me505

Resolves #302

2023-07-30 14:17 UTC, pavlovcik requested changes
That's not what the spec says

2023-07-30 18:06 UTC, me505 commented
oh. 
does it mean to just output a warning if someones sets a multiplier more than 1?

2023-07-31 11:44 UTC, me505 commented
ill assume that as there werent any replies

2023-08-02 10:38 UTC, me505 commented
@pavlovcik is this what you meant?

2023-08-02 10:40 UTC, pavlovcik requested changes

2023-08-02 10:40 UTC, pavlovcik commented on src/handlers/comment/handlers/multiplier.ts
> +      }. Please note that this feature is designed to reduce the bounty hunter salary.`;
"This feature is designed to limit the contributor's compensation for any bounty on the current repository due to other compensation structures (i.e. salary.) are you sure you want to use a bounty multiplier above `1`?"

2023-08-02 13:20 UTC, pavlovcik approved these changes

2023-08-02 13:21 UTC, pavlovcik commented on src/handlers/comment/handlers/multiplier.ts
> +    if (bountyMultiplier <= 1) {
Wait isn't this saying for less than 1?

2023-08-02 13:26 UTC, me505 commented on src/handlers/comment/handlers/multiplier.ts
> +    if (bountyMultiplier <= 1) {
uhh :skull:

2023-08-02 13:28 UTC, pavlovcik approved these changes

2023-08-02 13:28 UTC, merged