chore: refactor autopay to paymentPermitMaxPrice
ubiquity/ubiquibot pull request #568
Opened 2023-07-31 16:40 UTC by EtherealGlow

Resolves #493

2023-08-02 10:25 UTC, EtherealGlow commented
@0xcodercrane should work now

2023-08-03 12:26 UTC, 0xcodercrane approved these changes

2023-08-03 12:27 UTC, 0xcodercrane commented
Before merge the PR, I want to get the corresponding configuration refactor prs by @rndquu

2023-08-04 22:42 UTC, rndquu commented
> Before merge the PR, I want to get the corresponding configuration refactor prs by @rndquu

- https://github.com/ubiquity/ubiquibot-config/pull/6
- https://github.com/ubiquibot/ubiquibot-config/pull/5

2023-08-07 07:01 UTC, 0xcodercrane requested changes

2023-08-07 07:01 UTC, 0xcodercrane commented on src/handlers/payout/action.ts
> +  if (!paymentPermitMaxPrice) {
```suggestion
  if (paymentPermitMaxPrice == 0) {
```

Suggesting above to avoid confustion of `paymentPermitMaxPrice` type.

2023-08-07 07:02 UTC, 0xcodercrane submitted a review, later dismissed

2023-08-07 07:03 UTC, 0xcodercrane commented
@EtherealGlow would you resolve the conflicts for the merge?

2023-08-07 09:37 UTC, EtherealGlow commented
@0xcodercrane done

2023-08-07 09:42 UTC, 0xcodercrane approved these changes

2023-08-07 09:43 UTC, merged