feat: read from env
ubiquity/ubiquibot pull request #639
Opened 2023-08-19 16:46 UTC by EtherealGlow

Resolves #619

2023-08-20 07:34 UTC, whilefoo requested changes
Because we are reading from env I think it's better to put these variables in the [loadConfig](https://github.com/ubiquity/ubiquibot/blob/f6e99dfb406559a044969bb82aff478daae172cd/src/bindings/config.ts#L75C6-L75C6) but leave the default values in this file

2023-08-20 08:27 UTC, EtherealGlow commented
Doesn't load config function return object of type bot config or am I getting confused

2023-08-21 09:41 UTC, whilefoo commented
yes but this is internal bot config, not like ubiquibot-config.yaml

2023-08-22 16:50 UTC, EtherealGlow commented
i didnt exactly understand the spec

2023-08-23 07:19 UTC, whilefoo requested changes

2023-08-23 07:19 UTC, whilefoo commented on src/bindings/config.ts
> +      DEFAULT_TIME_RANGE_FOR_MAX_ISSUE: process.env.DEFAULT_TIME_RANGE_FOR_MAX_ISSUE
the variable names should be in snakeCase and I think it's better to put them in unassign object because it's related to unassigning

2023-08-23 07:19 UTC, whilefoo commented on src/helpers/issue.ts
> +  const botConfig = await loadConfig(context);
this is not how you load the config, you should use `getBotConfig`

2023-08-24 19:19 UTC, whilefoo requested changes

2023-08-24 19:19 UTC, whilefoo commented on src/types/config.ts
> +  defaultTimeRangeForMaxIssueEnabled: Type.Boolean(),
why is it called default?

2023-08-25 09:50 UTC, whilefoo requested changes

2023-08-25 09:50 UTC, whilefoo commented on src/types/config.ts
> +  defaultTimeRangeForMaxIssueEnabled: Type.Boolean(),
```suggestion
  timeRangeForMaxIssueEnabled: Type.Boolean(),
```

2023-08-25 09:50 UTC, whilefoo commented on src/types/config.ts
> +  defaultTimeRangeForMaxIssue: Type.Number(),
```suggestion
  timeRangeForMaxIssue: Type.Number(),
```

2023-08-26 12:46 UTC, whilefoo approved these changes

2023-08-26 15:13 UTC, merged