Remove unused declaration
ubiquity/ubiquibot pull request #642
Opened 2023-08-20 11:43 UTC by pavlovcik

I got sick of seeing this in every pull request review.

<img width="490" alt="Screenshot 2023-08-20 at 20 43 16" src="https://github.com/ubiquity/ubiquibot/assets/4975670/de97fb0e-eb73-48cf-8e10-60a8d41da7c8">

2023-09-06 14:18 UTC, rndquu submitted a review, later dismissed

2023-09-06 15:16 UTC, whilefoo commented on src/adapters/supabase/helpers/client.ts
> -    logger.info(`Creating a new wallet_table record done, { data: ${JSON.stringify(_data)} }`);
that warning is weird because `_data` is used here

2023-09-08 02:04 UTC, 0xcodercrane requested changes

2023-09-08 02:04 UTC, 0xcodercrane commented on src/adapters/supabase/helpers/client.ts
> +    logger.info(`Creating a new wallet_table record done, { data: ${JSON.stringify(data)} }`);
doesn't make sense to log `data` cause its already stalled data once a new record is added.

```suggestion
    logger.info(`Creating a new wallet_table record done, { data: ${JSON.stringify(data)}, address: $address }`);
```

2023-09-08 02:10 UTC, merged