Db check duplicates
ubiquity/ubiquibot pull request #656
Opened 2023-08-22 16:41 UTC by byteballet

Resolves #574

2023-08-23 01:49 UTC, pavlovcik reviewed
I just updated the specification, but I don't see a mechanism to sync the username. Do you have that here?

2023-08-23 05:19 UTC, byteballet commented
> I just updated the specification, but I don't see a mechanism to sync the username. Do you have that here?

Sorry, I thought it will be a new issue. I will update.

2023-08-23 07:15 UTC, pavlovcik commented
> > I just updated the specification, but I don't see a mechanism to sync the username. Do you have that here?
> 
> 
> 
> Sorry, I thought it will be a new issue. I will update.

That might have made sense actually. Hopefully it's fine I updated the existing one!

2023-08-24 00:34 UTC, pavlovcik commented
@rndquu rfc

I figured caching the username for reads is useful to save on network requests. It seems useful to be able to directly refer to the username from the database.

2023-08-24 00:36 UTC, byteballet commented
> I figured caching the username for reads is useful to save on unnecessary network requests to the GitHub API. Intuitively to me it seems useful to be able to directly refer to the username from the database. But at the same time, perhaps it's a waste of storage space.

Also I think there is no big difference between reading database and using github api.

2023-08-24 09:24 UTC, whilefoo commented
I took a quick look and we never get username from database. Most of the time all user data is available in the webhook payload.

2023-08-24 10:28 UTC, pavlovcik commented on package-lock.json
This should not be here. We use yarn. Please remove.

2023-08-24 10:29 UTC, pavlovcik commented on src/handlers/comment/handlers/query.ts
> +  getUser;
```suggestion
```

2023-08-24 10:30 UTC, pavlovcik commented
> I took a quick look and we never query username from database. Most of the time all user data is available in the webhook payload.

Looks like we should get rid of the username entirely then.

2023-08-24 11:40 UTC, byteballet commented
> Looks like we should get rid of the username entirely then.

Yes, that must be the solution.

2023-08-25 23:42 UTC, Draeieg commented
let me know when this is ready to go into QA

2023-08-26 00:35 UTC, byteballet commented
> let me know when this is ready to go into QA

I guess it's now.

2023-09-05 09:59 UTC, rndquu commented
@byteballet Could you resolve the conflicts one more time?

@whilefoo @wannacfuture Could you help with the review?

2023-09-05 11:14 UTC, wannacfuture reviewed
@byteballet  Could you provide QA? Just wanted to make sure if its working as normal.

2023-09-05 12:28 UTC, whilefoo requested changes
Code looks mostly good. Please post QA.

2023-09-05 12:28 UTC, whilefoo commented on src/handlers/comment/handlers/query.ts
>    const user = matches?.[1];
```suggestion
  const username = matches?.[1];
```

2023-09-05 12:28 UTC, whilefoo commented on src/handlers/comment/handlers/query.ts
> +    const { id: user_id } = (await getUser(user)) ?? {};
```suggestion
    const user = await getUser(user);
    if (!user) {
      logger.info(`Error retrieving data about user @${username}`);
      return `Error retrieving data about user @${username}`;
    }
```

2023-09-05 12:28 UTC, whilefoo commented on src/handlers/comment/handlers/query.ts
> +    const walletInfo = await getWalletInfo(user, id?.toString(), user_id || 0);
```suggestion
    const walletInfo = await getWalletInfo(user, id.toString(), user.id);
```

2023-09-12 09:15 UTC, 0xcodercrane requested changes

2023-09-12 11:28 UTC, byteballet commented on supabase/migrations/20230821160747_add_id.sql
> +ALTER TABLE wallets
Okay, I will have a look.
Thanks

2023-09-26 06:16 UTC, closed without merging