Default config and config change
ubiquity/ubiquibot pull request #668
Opened 2023-08-25 10:16 UTC by whilefoo

Related to:
https://github.com/ubiquity/ubiquibot/pull/662#discussion_r1303166625
https://github.com/ubiquity/ubiquibot/pull/662#discussion_r1303198292

2023-08-25 21:31 UTC, pavlovcik requested changes
There's way more elements supported. Did you check my draft? 

I also added a link to the readme in the last section related to the default config. 

https://github.com/syntax-tree/mdast#nodes

2023-08-26 16:14 UTC, whilefoo commented
I looked at [Markdown-to-HTML](https://github.com/syntax-tree/mdast-util-to-hast) converter and added all tags that are supported.

2023-08-26 18:38 UTC, pavlovcik requested changes
This still seems like way too little. I'm not sure what happened to my changes I made to `ubiquibot-config-default.json` but perhaps I never merged them in.

https://github.com/pavlovcik/ubiquibot/blob/refactor/general/ubiquibot-config-default.json#L96-L128

---

You can also see some comments I left when I brirefly had it as a `.jsonc` file.

https://github.com/pavlovcik/ubiquibot/blob/691e79df852d718001b58993791eb9aaa5b07223/ubiquibot-config-default.jsonc#L92-L126

--- 

According to my vscode: you clobbered my full list addition in https://github.com/ubiquity/ubiquibot/blob/a67607009a2d50fc0d1282ec289478db191ad053/ubiquibot-config-default.json

Last existed in https://github.com/ubiquity/ubiquibot/blob/fc0516e248cbaee4fc3b7c871a4e652d5e836914/ubiquibot-config-default.json

No idea why it doesnt show you deleting it in your commit. Seems that it magically disappeared. Even when directly comparing the history on github https://github.com/ubiquity/ubiquibot/commits/a67607009a2d50fc0d1282ec289478db191ad053/ubiquibot-config-default.json

Comparing bases (`...`) its not there https://github.com/ubiquity/ubiquibot/compare/61b4dd09b0a91b6d4d763a080b3a616e4a3e5bf4...7c6f399b039a874e93ed99c56925d3f7d998de75
[Three-dot Git diff comparison](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-git-diff-comparison)
The three-dot comparison shows the difference between the latest common commit of both branches (merge base) and the most recent version of the topic branch.

Comparing commits directly (`..`) you can see the removal 
https://github.com/ubiquity/ubiquibot/compare/61b4dd09b0a91b6d4d763a080b3a616e4a3e5bf4..7c6f399b039a874e93ed99c56925d3f7d998de75
[Two-dot Git diff comparison](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#two-dot-git-diff-comparison)
The two-dot comparison shows the difference between the latest state of the base branch (for example, main) and the most recent version of the topic branch.

2023-09-06 16:06 UTC, rndquu submitted a review, later dismissed
So the current PR adds html config elements for the comment incentives feature.

When this [PR](https://github.com/ubiquity/ubiquibot/pull/688) is merged then comment incentives reward calculation is going to work this way (@whilefoo pls correct me if I'm wrong):
1. The bot gets and parses comments in `md` format
2. For each `md` comment node (i.e. `Heading` or `ListItem`) the bot finds the corresponding html config [here](https://github.com/ubiquity/ubiquibot/blob/9d0e958c9fd7e5bde6418090b2bc82b42e6285e7/ubiquibot-config-default.json#L98) and applies price accordingly

Overall most of the `md` elements are supported (i.e. have their corresponding html tags) which is enough for tweaking comment incentive rewards

2023-09-07 08:39 UTC, whilefoo commented
Yes that's correct

2023-09-10 15:39 UTC, pavlovcik commented
@whilefoo can you answer if you included everything? It seems like there could be many more tags supported.

2023-09-14 02:14 UTC, wannacfuture commented
lets add `pre` and `ol` @whilefoo

2023-09-17 17:40 UTC, whilefoo commented
now it should support all tags

2023-09-18 07:02 UTC, pavlovcik commented on ubiquibot-config-default.json
> +      },
```suggestion
        "ol": 0
        "b": 0
        "i": 0
      },
```

I'm unsure if these are valid on GitHub but the intent here is targeting bold and italics.

2023-09-18 07:03 UTC, pavlovcik commented on ubiquibot-config-default.json
> +      },
Looks like its actually `em` on GitHub?

2023-09-18 07:03 UTC, pavlovcik approved these changes

2023-09-25 09:36 UTC, whilefoo commented
will be fixed in https://github.com/ubiquity/ubiquibot/pull/818

2023-09-25 09:36 UTC, closed without merging