feat: add repo specific wallet support
ubiquity/ubiquibot pull request #747
Opened 2023-09-10 18:31 UTC by me505

Resolves #719

2023-09-10 18:52 UTC, pavlovcik commented
Please demo this working by configuring your test org and showing a repo specific permit and a generic org permit.

2023-09-12 11:54 UTC, me505 commented
do i have to remove merged configs or no, i dont really get why not if no

2023-09-15 04:46 UTC, me505 commented
hmm its reading the parsed repo and getting the decrypted private key but its reading undefined after getPrivateKey function call, very weird

2023-09-15 04:53 UTC, me505 commented
@pavlovcik 
https://github.com/me505/ubiquibot/issues/5

2023-09-15 04:53 UTC, me505 commented
https://github.com/me505/ubiquibot/blob/development/.github/ubiquibot-config.yml

2023-09-15 04:54 UTC, me505 commented
the failed attempts were because i was dumb while trying to generate a key

2023-09-15 08:26 UTC, whilefoo requested changes
why are you adding typescript interfaces?

2023-09-15 09:50 UTC, me505 commented
Should I only modify wide repo config?

2023-09-17 13:44 UTC, whilefoo requested changes
you can delete org config type because now repo and org configs have the same format

2023-09-17 13:44 UTC, whilefoo commented on src/utils/private.ts
> +  const privateKeyDecrypted = await (async () => {
why is this anonymous function?

2023-09-17 14:42 UTC, me505 commented
@whilefoo done

2023-09-17 15:26 UTC, me505 commented
@whilefoo how to setup org wallet

2023-09-17 15:29 UTC, whilefoo commented
> @whilefoo how to setup org wallet

it's `private-key-encrypted` field in org and repo config. you can [generate](https://vanity-eth.tk/) a random one

2023-09-17 15:33 UTC, me505 commented
https://github.com/me505/ubiquibot/issues/7 for repo wallet

2023-09-17 16:10 UTC, me505 commented
https://github.com/me505-qa/ubiquibot/issues/1 org permit

2023-09-17 16:11 UTC, me505 commented
@whilefoo idk how to prove it to you that this is a org permit but this is it

2023-09-18 07:20 UTC, 0xcodercrane submitted a review, later dismissed
The codebase looks good. will wait for @me505.

2023-09-18 09:13 UTC, me505 commented
What do you want me for?

2023-09-18 09:31 UTC, whilefoo approved these changes

2023-09-19 08:18 UTC, me505 commented
@pavlovcik can you review this?

2023-09-19 17:52 UTC, 0xcodercrane approved these changes

2023-09-19 17:53 UTC, merged

2023-09-19 17:54 UTC, 0xcodercrane commented
> What do you want me for?

oh sorry my bad. I wanted to tag whilefoo lol

2023-09-20 08:26 UTC, pavlovcik commented
Can you guys verify the following scenarios hold true with this implementation?

1. The org sets an org wallet; no repo wallet set; payouts generated from org wallet.
2. The org sets an org wallet; repo wallet set; payouts generated from repo wallet.

2023-09-20 09:30 UTC, whilefoo commented
> Can you guys verify the following scenarios hold true with this implementation?
> 
> 1. The org sets an org wallet; no repo wallet set; payouts generated from org wallet.
> 2. The org sets an org wallet; repo wallet set; payouts generated from repo wallet.

I just tested and can confirm