feat: extract time duration with ms
ubiquity/ubiquibot pull request #756
Opened 2023-09-12 08:35 UTC by wannacfuture

Resolves #431

Quality Assurance: https://github.com/wannacfuture/Battleship/issues/88

2023-09-12 09:34 UTC, 0xcodercrane requested changes

2023-09-12 09:34 UTC, 0xcodercrane commented on src/helpers/shared.ts
> +  return ms(label.name.split("<")[1]) / 1000;
could we think of a way to use regex here rather than using `split`?

2023-09-12 10:56 UTC, rndquu approved these changes
Works fine

2023-09-13 13:55 UTC, wannacfuture commented
seems can be merged due to its a small fix. @pavlovcik

2023-09-14 08:07 UTC, 0xcodercrane approved these changes

2023-09-14 08:08 UTC, merged