feat: enable comment incentives on closed issues
ubiquity/ubiquibot pull request #762
Opened 2023-09-12 16:33 UTC by EtherealGlow

Resolves #754

Quality Assurance: None for now

2023-09-12 16:33 UTC, EtherealGlow commented
i cant see anything that would stop a permit from generating in post
@pavlovcik

2023-09-13 02:41 UTC, 0xcodercrane requested changes
Looks like its still in progress. converted it to a draft.

2023-09-13 02:51 UTC, EtherealGlow commented
@0xcodercrane i cant see anything that would make a incentive permit to stop generating

2023-09-13 03:34 UTC, 0xcodercrane commented
> @0xcodercrane i cant see anything that would make a incentive permit to stop generating

https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/pricing/action.ts#L17

can you see this line? @EtherealGlow

2023-09-13 06:52 UTC, EtherealGlow commented
But what about incentives tho, incentives don't have a price label

2023-09-14 02:22 UTC, wannacfuture commented
> @0xcodercrane But what about incentives tho, incentives don't have a price label

you can refer `incentivizeComments` and `incentivizeCreatorComment`

2023-09-16 07:08 UTC, EtherealGlow commented
https://github.com/EtherealGlow/ubiquibot/issues/18 on this it tried generating conversation rewards.
https://github.com/EtherealGlow/ubiquibot/issues/16 on this it generated conversation rewards after reopening the issue

2023-09-16 07:08 UTC, EtherealGlow commented
@wannacfuture can you review this

2023-09-16 12:41 UTC, pavlovcik commented
> https://github.com/EtherealGlow/ubiquibot/issues/18 on this it tried generating conversation rewards.
> 
> https://github.com/EtherealGlow/ubiquibot/issues/16 on this it generated conversation rewards after reopening the issue 

This doesn't generate rewards on the meta issue why are you submitting this as completed work?

2023-09-16 13:26 UTC, EtherealGlow commented
Meta issue?

2023-09-18 14:43 UTC, EtherealGlow commented
man now somehow my permits are broken, @Draeieg can you help me qa this because i cannot

2023-09-18 14:43 UTC, EtherealGlow commented
> > [EtherealGlow#18](https://github.com/EtherealGlow/ubiquibot/issues/18) on this it tried generating conversation rewards.
> > [EtherealGlow#16](https://github.com/EtherealGlow/ubiquibot/issues/16) on this it generated conversation rewards after reopening the issue
> 
> This doesn't generate rewards on the meta issue why are you submitting this as completed work?

it was prob because all incentive elements were set to 0
my fault on that one

2023-09-21 08:23 UTC, whilefoo commented
@EtherealGlow what's the status of this PR? If it's done, can you post QA? Also resolve the conflicts

2023-09-21 09:20 UTC, EtherealGlow commented
Incentives aren't working even if I do getPrivateKey(cipher) directly

2023-09-21 21:11 UTC, whilefoo reviewed
I think we shouldn't generate permit again if the issue is reopened and closed because we have one permit per user per issue rule so the user will only be able to claim one permit. Also I don't see this being part of the specification - it's only about generating issue creator and conversation rewards for parent issues.

@EtherealGlow try pulling latest changes from development because there was a big change to incentives

2023-09-25 09:19 UTC, whilefoo requested changes
Can you post QA? 
Also please learn how to use Git without force pushing, we won't be able to process your future PRs if you keep using force push

2023-09-25 09:19 UTC, whilefoo commented on src/handlers/payout/post.ts
>    const assignee = assignees.length > 0 ? assignees[0] : undefined;
`assignees` and `assignee` is not used anymore if I see correctly

2023-09-27 13:39 UTC, EtherealGlow commented
[qa](https://github.com/EtherealGlow/ubiquibot/pull/25)

2023-09-27 13:39 UTC, EtherealGlow commented
the bot requested review from me but idk why the bot requested 2 times, does someone know why?

2023-09-27 13:42 UTC, EtherealGlow commented
will do this shortly,
fixing the bot is harder than any issue i have ever done

2023-09-29 06:11 UTC, EtherealGlow commented
@whilefoo how would i qa, my wallet doesnt have enough balance and it refuses to generate a permit

2023-09-29 12:02 UTC, wannacfuture commented
> @whilefoo how would i qa, my wallet doesnt have enough balance and it refuses to generate a permit

@EtherealGlow Bot is able to generate permit URL even you don't have enough balance.

You cannot just claim it when you go to that url(saying insuficcient fund).

2023-09-29 12:04 UTC, EtherealGlow commented
> > @whilefoo how would i qa, my wallet doesnt have enough balance and it refuses to generate a permit
> 
> @EtherealGlow Bot is able to generate permit URL even you don't have enough balance.
> 
> You cannot just claim it when you go to that url(saying insuficcient fund).

https://github.com/me505/ubiquibot/issues/10#issuecomment-1736926872

2023-09-29 12:17 UTC, wannacfuture commented
> > > @whilefoo how would i qa, my wallet doesnt have enough balance and it refuses to generate a permit
> > 
> > 
> > @EtherealGlow Bot is able to generate permit URL even you don't have enough balance.
> > You cannot just claim it when you go to that url(saying insuficcient fund).
> 
> [me505#10 (comment)](https://github.com/me505/ubiquibot/issues/10#issuecomment-1736926872)

Please take a closer look at the `generatePermitForComments` function.  @me505 
I don't think its releated to the funds in your wallet. There is no feature to check the funds in the wallet in that function.

The reason of that error message is not your insufficient funds in your wallet.
I bet it is related to missing account or the reward value is 0 or higher than maxPermitPrice.

2023-09-29 12:27 UTC, EtherealGlow commented
@wannacfuture any idea why the result of generatePermitForComments is undefined?

2023-09-29 12:31 UTC, wannacfuture commented
> @wannacfuture any idea why the result of generatePermitForComments is undefined?

Like I said, I'm assuming that the reward value is calculated as 0 or account or missing or is higher than the maxPermitPrice.

You can check it adding console logs to that function.

2023-09-30 09:12 UTC, closed without merging