feat: follow up with reviewer
ubiquity/ubiquibot pull request #783
Opened 2023-09-19 10:45 UTC by EtherealGlow

Resolves #322

Quality Assurance:

2023-09-19 10:46 UTC, EtherealGlow commented
same logic as this https://github.com/ubiquity/ubiquibot/pull/708

2023-09-19 10:47 UTC, EtherealGlow commented
just it follows up with the reviewer/reviewers now instead of doing nothing

2023-09-20 08:24 UTC, wannacfuture reviewed
You need to check the pending time duration.

- The bot should follow up the reviewer who has been delayed for some days(maybe 3 or 5) after being requested for the review.

- Also the delay duration should be configuratble.

2023-09-21 10:13 UTC, EtherealGlow commented
doesnt this execute whenever the bot tries to follow up with reviewer?

2023-09-23 14:40 UTC, pavlovcik commented
QA should always be posted thats why its part of the pull request template.

2023-09-25 08:56 UTC, EtherealGlow commented
how would i even qa this?

2023-09-25 15:17 UTC, pavlovcik commented
Just post proof that it works on your fork

2023-09-27 01:53 UTC, 0xcodercrane commented
> how would i even qa this?

Please refer to the [README.md](https://github.com/ubiquity/ubiquibot#how-to-qa-any-additions-to-the-bot)

2023-09-27 13:40 UTC, EtherealGlow commented
[qa](https://github.com/EtherealGlow/ubiquibot/pull/25)
idk why the bot requested the review twice

2023-09-27 16:07 UTC, EtherealGlow commented
Now that I see it's prob because it's followed up a second time, as it was like 30s to follow up and 5mins to disqualify

2023-09-29 12:04 UTC, wannacfuture commented
Please read this again. @EtherealGlow 

https://github.com/ubiquity/ubiquibot/pull/783#pullrequestreview-1635004710

2023-10-08 15:27 UTC, EtherealGlow commented
@wannacfuture is there something in github api which provides the timestamps for the requested reviewers

2023-10-09 02:25 UTC, wannacfuture commented
> @wannacfuture is there something in github api which provides the timestamps for the requested reviewers

https://docs.github.com/en/rest/pulls/review-requests?apiVersion=2022-11-28#get-all-requested-reviewers-for-a-pull-request

you can use octokit. There is createdAt field representing the timestamp or review request for certain reviewers.
I think there is already a function for that: `getReviewRequests`

2023-10-09 05:23 UTC, EtherealGlow commented
```
{
  "users": [
    {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "teams": [
    {
      "id": 1,
      "node_id": "MDQ6VGVhbTE=",
      "url": "https://api.github.com/teams/1",
      "html_url": "https://github.com/orgs/github/teams/justice-league",
      "name": "Justice League",
      "slug": "justice-league",
      "description": "A great team.",
      "privacy": "closed",
      "notification_setting": "notifications_enabled",
      "permission": "admin",
      "members_url": "https://api.github.com/teams/1/members{/member}",
      "repositories_url": "https://api.github.com/teams/1/repos",
      "parent": null
    }
  ]
}
```
In this example response I couldnt find a createdAt field

2023-10-09 08:56 UTC, wannacfuture commented
@EtherealGlow 
Please take a look at the link I have provided again.

`/repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers`

2023-10-09 10:03 UTC, EtherealGlow commented
i am not following something because i think thats for requesting reviews not for getting all requested reviews
i could not find a created at in this
https://api.github.com/repos/EtherealGlow/ubiquibot/pulls/25/requested_reviewers

2023-10-10 12:24 UTC, whilefoo commented
@wannacfuture your API call is to request a reviewer not listing them like @EtherealGlow said. Instead of requested reviewers API, I think we can use [events API](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events), it includes event `review_requested` and has a timestamp.

2023-10-10 14:29 UTC, EtherealGlow commented
Ohhh that makes it easy

2023-10-11 14:44 UTC, whilefoo requested changes

2023-10-11 14:44 UTC, whilefoo commented on src/helpers/issue.ts
> +export const getAllIssueEvents = async () => {
this function already exists https://github.com/ubiquity/ubiquibot/blob/9d00d7f8be6e7b2eeb91f8a01246a1d9697881d7/src/helpers/issue.ts#L6

2023-10-11 14:44 UTC, whilefoo commented on src/utils/private.ts
> +  privateKeyDecrypted = await getPrivateKey(
you shouldn't commit this

2023-10-11 14:44 UTC, whilefoo commented on src/helpers/issue.ts
> +  return events[events.length - 1].created_at;
you need to check array length and if it's empty return null

2023-10-11 14:44 UTC, whilefoo commented on src/helpers/issue.ts
> +export const getRequestedReviewerStart = async (user: String) => {
```suggestion
export const getRequestedReviewerStart = async (user: string) => {
```

2023-10-11 14:44 UTC, whilefoo commented on src/helpers/issue.ts
> +  events = events.filter((e) => e.requested_reviewer?.login === user);
you can have just one filter `const filteredEvents = events.filter(e => e.event === "review_requested" && e.requested_reviewer?.login === user)`

2023-10-11 14:44 UTC, whilefoo commented on src/handlers/wildcard/unassign.ts
> +        if (!reviewRequestedAt) return false;
I don't think it's right to return false, because the function should still check other reviewers

2023-10-11 14:44 UTC, whilefoo commented on src/handlers/wildcard/unassign.ts
> +        expectedDate.setDate(expectedDate.getDate() + 3);
the delay should be configurable

2023-10-11 14:56 UTC, wannacfuture reviewed
@EtherealGlow 

Please make sure if the code runs successfully for the related issue. Not so sure but seems you are hardcoding -  not trying to run the bot and test it.

You will be needed to post a QA for every PRs.

2023-10-13 15:45 UTC, EtherealGlow commented
i am tired of this bot 😢 
```UbiquiBot Error: Invalid repo config: data must NOT have additional properties. Unnecessary properties: evmNetworkId undefined error ubiquibot EtherealGlow 1761727853 25```

2023-10-14 05:15 UTC, EtherealGlow commented
@whilefoo i even tried this config https://github.com/rndquu-org/test-repo/blob/6613b3bf91462018d1cec1b8f09eb27d072f8fc6/.github/ubiquibot-config.yml
still doesnt work

2023-10-14 05:34 UTC, pavlovcik requested changes

2023-10-14 05:34 UTC, pavlovcik commented on src/helpers/issue.ts
> +export const getRequestedReviewerStart = async (user: string) => {
```suggestion
export async function getRequestedReviewerStart (user: string) {
```

Changing all of these to named functions for stack traces.

2023-10-15 12:03 UTC, EtherealGlow commented
Any idea why the bot might not be working, the config is right

2023-10-15 15:48 UTC, whilefoo commented
@EtherealGlow can you link me your config?

2023-10-15 15:49 UTC, EtherealGlow commented
@whilefoo https://github.com/EtherealGlow/ubiquibot/blob/development/.github/ubiquibot-config.yml

2023-10-15 15:57 UTC, whilefoo commented
can you try running the bot with latest development branch and check if the issue is still present?

2023-10-20 14:26 UTC, EtherealGlow commented
wait just a day or two [this is ](https://github.com/ubiquity/ubiquibot/pull/840)almost done

2023-10-21 11:32 UTC, EtherealGlow commented
uhhh what

2023-10-21 11:33 UTC, closed without merging