build: added a settlements schema
ubiquity/ubiquibot pull request #833
Opened 2023-09-25 11:23 UTC by GaryThisSidee

Resolves #808

2023-09-25 11:57 UTC, seprintour commented
Check comment on issue @GaryThisSidee

2023-09-25 17:14 UTC, pavlovcik commented
My mistake for not clarifying but the requirements inherit from the parent issue 


> The bot is expected to be stable after these changes are implemented which implies that all of the functions that interact with the database should also be refactored to accomodate this new architecture.

2023-10-03 19:32 UTC, whilefoo requested changes
please follow naming convention

2023-10-03 19:32 UTC, whilefoo commented on supabase/migrations/20230925111522_settlements.sql
> +CREATE TABLE IF NOT EXISTS Settlements (
```suggestion
CREATE TABLE IF NOT EXISTS settlements (
```

2023-10-03 19:32 UTC, whilefoo commented on supabase/migrations/20230925111522_settlements.sql
> +    userId 	 int8 NOT NULL,
```suggestion
    user_id 	 int8 NOT NULL,
```

2023-10-05 18:08 UTC, whilefoo commented
@seprintour

2023-10-05 18:09 UTC, seprintour commented
@whilefoo this is not my PR, it's incomplete anyway and it's supposed to be closed as the issue has been released to the devpool

2023-10-05 18:13 UTC, whilefoo commented
oh sorry!

2023-10-05 18:17 UTC, closed without merging