chore: update and improve README.md
ubiquity/ubiquibot pull request #844
Opened 2023-09-27 03:27 UTC by molecula451

Resolves #

Quality Assurance:

2023-10-09 02:36 UTC, wannacfuture reviewed
Looks Good to me. 👍

This will help new contributors who having issues running the bot.
@ubiquity/software-development Please take a look

2023-10-09 06:37 UTC, rndquu submitted a review, later dismissed

2023-10-09 08:54 UTC, wannacfuture submitted a review, later dismissed

2023-10-12 01:30 UTC, cuddle-dev commented on README.md
> +2. Create a new organization at [Mezmo](https://app.mezmo.com/). Add `LOGDNA_INGESTION_KEY` to the `.env` file:
Looks like it has been deprecated. We don't use logdna for the real-time logger. moved them to the supabase.

2023-10-12 01:31 UTC, 0xcodercrane commented on README.md
> +2. Create a new organization at [Mezmo](https://app.mezmo.com/). Add `LOGDNA_INGESTION_KEY` to the `.env` file:
@molecula451

2023-10-12 10:25 UTC, whilefoo requested changes

2023-10-12 10:25 UTC, whilefoo commented on README.md
> +- Copy `.env.example` to `.env` (do not rname .env.example, just make a copy)
```suggestion
- Copy `.env.example` to `.env` (do not rename .env.example, just make a copy)
```

2023-10-12 10:25 UTC, whilefoo commented on README.md
>  1. Create a new project at [Supabase](https://supabase.com/). Add `Project URL` and `API Key` to the `.env` file:
Maybe you can clarify where to get URL and API key. 
Something like `Go to Project Settings and click on the API section, get the Project URL and API key for service_role/secret.`

2023-10-25 04:49 UTC, molecula451 commented
everyone check QA https://github.com/molecula451/ubiquibot/blob/update-readme/README.md

2023-10-25 04:50 UTC, molecula451 commented on README.md
> +2. Create a new organization at [Mezmo](https://app.mezmo.com/). Add `LOGDNA_INGESTION_KEY` to the `.env` file:
done purged everything about mezmo @0xcodercrane

2023-10-25 13:35 UTC, molecula451 commented
it looks like pavlovcik wants to also integrate the supabase migration thing https://github.com/ubiquity/ubiquibot/issues/838#issuecomment-1734546986 but! the supabase readme it's complete and i think a dev should be aware of this module at the repo and how to handle the inner stuff of supabase, e.g migrations what do you guys think? @rndquu @0xcodercrane @wannacfuture @whilefoo

2023-10-25 13:42 UTC, pavlovcik commented
> everyone check QA https://github.com/molecula451/ubiquibot/blob/update-readme/README.md

I skimmed this. It looks really substantial! I do not have time to test the set up but I expect that the other team members should try from A to Z to set up a new bot and follow that tutorial.

2023-10-25 14:34 UTC, wannacfuture commented
> > everyone check QA https://github.com/molecula451/ubiquibot/blob/update-readme/README.md
> 
> I skimmed this. It looks really substantial! Good work! I do not have time to test the set up right now but I expect that the other team members should try from A to Z to set up a new bot and follow that tutorial.

I have already tried this readme(setting up the bot) and looks good to me. 👍

2023-10-30 10:47 UTC, pavlovcik approved these changes
I approve based on @wannacfuture's review. However it would be appreciated if we could get at least one more before merging.

2023-10-31 14:08 UTC, molecula451 commented
yeah i agree @rndquu @0xcodercrane

2023-11-01 10:26 UTC, rndquu approved these changes

2023-11-02 22:00 UTC, molecula451 commented
@0xcodercrane crane let's get an eagle eye on this one to help pavlovcik get it merge

2023-11-03 01:24 UTC, wannacfuture approved these changes

2023-11-08 12:38 UTC, pavlovcik commented
@whilefoo when you approve this will automatically merge.

2023-11-09 06:04 UTC, molecula451 commented
@whilefoo your review it's important for everyone here

2023-11-09 16:01 UTC, whilefoo approved these changes

2023-11-09 16:01 UTC, merged